pipeline {
    agent any

    environment {
        IMAGE_NAME = "dockerhubusername/messaging_app"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/YOUR_USERNAME/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                pip3 install pytest pytest-html
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                pytest messaging_app --html=report.html --self-contained-html
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $IMAGE_NAME:latest .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $IMAGE_NAME:latest
                    '''
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'report.html'
        }
    }
}
