#!/bin/bash
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD
